### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by tyeeman** [epsalt/epsalt.ca#2]
Is it possible to build on Windows. Make is for Linux isn't it or is there an equivalent exe for Windows?

**Comment by epsalt** [comment]
It should be possible to build the site on Windows. The `build` section of the [makefile](https://github.com/epsalt/epsalt.ca/blob/master/makefile) can be converted to a Windows Batch script. Something along these lines:

```batch
if exist ".\site\" (
    rmdir /s /q ".\site\"   
)
mkdir ".\site\"
xcopy /s /q ".\static\." ".\site"
sassc ".\scss\site.scss" -s compressed > ".\site\css\styles.min.css"
python ".\bin\generator.py"
```

**Comment by tyeeman** [comment]
Ok, I'm running the above in a batch file and all works except the last line and I get this error - 
```
g:\laragonServerPortable\www\epsalt>python ".\bin\generator.py"
Traceback (most recent call last):
  File ".\bin\generator.py", line 12, in <module>
    from dateutil.parser import parse
ModuleNotFoundError: No module named 'dateutil'
```
I ran the pip installer and got this -
```
c:\Python37>pip install python-dateutil
Requirement already satisfied: python-dateutil in c:\python37\lib\site-packages (2.8.0)
Requirement already satisfied: six>=1.5 in c:\python37\lib\site-packages (from python-dateutil) (1.1
2.0)
```
So pip says I got it but epsalt says no??

**Comment by epsalt** [comment]
Could be a pip/python version problem? You may be installing the packages for Python 3 but Python 2 is getting called in the `python ".\bin\generator.py"` line. Changing `python` in that line to your full Python 3 executable location might work.

Alternatively you could try using a Python 3 virtualenv and installing dependencies with `pip install -r requirements.txt`. That is what I am doing in my dev environment to build the site.

**Comment by tyeeman** [comment]
Ok, I added the full path for python 3 and get this error - 
```
41 File(s) copied
Traceback (most recent call last):
  File ".\bin\generator.py", line 256, in <module>
    SiteGenerator(DIRS, SITE, MarkdownReader, JinjaRenderer).publish()
  File ".\bin\generator.py", line 41, in __init__
    self.read = reader().read
  File ".\bin\generator.py", line 215, in __init__
    self.md = Markdown(self.extensions, output_format='html5')
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by tyeeman** [comment]
To get it working I did this - 
```
pip install "markdown<3.0.0"
```

**Comment by epsalt** [comment]
Looks like there may have been a [breaking change](https://python-markdown.github.io/change_log/release-3.0/#positional-arguments-deprecated) in the `Markdown` package since the version of `Markdown~=2.6.11` the code in [generator.py](https://github.com/epsalt/epsalt.ca/blob/master/bin/generator.py) relies on.

Can check that your package versions agree with the [requirements.txt](https://github.com/epsalt/epsalt.ca/blob/master/requirements.txt) file in the repo?

**Comment by tyeeman** [comment]
Is there a way to have both markdown versions work? Are you going to have to update your code to make ver. 3 work?

FYI, I just uploaded your test site to surge.sh and everytime I click a link Firefox asks me if I want to open or save the file. I think it's because you have decided to not have html extensions on your links. I will try Netlify now and update this post.

**Comment by epsalt** [comment]
- I don't have any immediate plans to update to support the new version of the Markdown package
- Content-Type for extensionless files gets set to 'text/html' in the `deploy` section of the Makefile. I don't have any experience with Netlify or Surge so I can't help you there.

This is the code for my personal website and I am just dealing with my own use case currently. Feel free to work on your own fork though!

If you are looking for a static site generator with actual support I recommend trying one of the excellent options on [https://www.staticgen.com/](https://www.staticgen.com/).

**Comment by tyeeman** [comment]
Ok, thanks.
